### PR TITLE
Write add command to pry with new syntax, this will make pry-byebug gem ...

### PR DESCRIPTION
**Pull request by zw963**
...worked in $LOAD_PATH correctly.

Hi, I rewrite three command with new Pry command support syntax.

And then, When I put pry-byebug directly into $LOAD_PATH, it worked for me!

### CODE REVIEW

**Comment by zw963** [comment]
.... Failed,  I will try to discovery this later.

**Comment by deivid-rodriguez** [comment]
Ok, I'll review the PR once it's passing in Travis.

**Comment by deivid-rodriguez** [comment]
Thanks, by the way! :+1:

**Comment by zw963** [comment]
I still not know why cause this, I just rewrite commands, no change else.

perhaps it not as simple as I thought, i give up again. sorry.

**Comment by deivid-rodriguez** [comment]
Closing since this has been addressed already.

**Pull request closed without merging**
