### PR TITLE
Add frame nav commands up, down and frame through byebug

### PR DESCRIPTION
**Pull request by christian-schulze**
Adds frame nav commands `up`, `down` and `frame` through **byebug**.

Note: original PR was #55.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
No problem. So is it ready to merge? Did you try other next/step vs up/down combinations?

Last thing, add a CHANGELOG entry!

**Comment by christian-schulze** [comment]
Yes I've ran various combinations of up, down, next and step. Haven't been able to break it so far.

I've added a changelog entry and bumped the version to 3.1.0, is this correct or should it be 3.0.1?

Otherwise I'm cool with merging :+1:

**Comment by deivid-rodriguez** [comment]
Merged and released! THANKS!!!

**Comment by christian-schulze** [comment]
Awesome, thanks for your patience.

**Comment by deivid-rodriguez** [comment]
:+1:

**Pull request merged**
