### PR TITLE
Using the new release of byebug

### PR DESCRIPTION
**Pull request by krainboltgreene**
The tests should tell us if we're using any of the changed public API.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
:+1: Thanks!

I don't trust current coverage a lot so I'd appreciate manual testing too.

**Comment by tmertens** [comment]
@deivid-rodriguez Can this get released sooner than later?  I don't use it a lot TBQH so I can't speak to your request for manual testing, but there is a major problem with byebug v4 where it halts the server thread when trying to debug capybara acceptance tests, thus making it impossible to use pry when debugging acceptance tests.  This issue is resolved in byebug v5.

**Comment by deivid-rodriguez** [comment]
Why don't you use `byebug 5`?

**Comment by tmertens** [comment]
@deivid-rodriguez We have pry-plus, which depends on pry-byebug, which depends on byebug '~> 4.x'.

Actually probably the best solution which would resolve both issues would be to just change the dependency in pry-byebug to `>= 4` instead of `~> 4.0` (current) or `~> 5.0` (as proposed by this PR)

**Comment by deivid-rodriguez** [comment]
I've merged this. Hopefully support is easier to try now.

**Comment by tmertens** [comment]
Update: We're doing further investigation of the above issue, one of our engineers found it may not be directly related to byebug.  We are continuing investigation, but this may be a lower priority than first thought (although updating the dependency would still be nice).

**Comment by tmertens** [comment]
Thanks @deivid-rodriguez

**Comment by deivid-rodriguez** [comment]
No problem!

**Comment by dgilperez** [comment]
Great! Can you bump and release, please?

**Comment by deivid-rodriguez** [comment]
Done!

**Comment by dgilperez** [comment]
Thanks a bunch!

**Pull request merged**
