### PR TITLE
Get ready for 3.4.3

### LINKED ISSUE #123: Dep on byebug ~> 9.0 breaking for versions of ruby before 2.2
Get this error when trying to install pry-byebug 3.4.0

```
Installing byebug 9.1.0 with native extensions
--

Gem::InstallError: byebug requires Ruby version >= 2.2.0.
```

It looks like byebug 9.1.0 only supports Ruby 2.2.0. It was released today. https://rubygems.org/gems/byebug

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
I'll be releasing this version as the last version supporting ruby 2.0 & ruby 2.1.

Fixes #123.

### CODE REVIEW

**Comment by aried3r** [comment]
Does that mean there'll be another release soon with support for byebug 9.1+?

**Comment by deivid-rodriguez** [comment]
Yes. Except for the "soon" part which I'm not really sure of.

**Comment by deivid-rodriguez** [comment]
@aried3r I'll be soon in the end :smile:. Would you like to give #126 a try before I release it?

**Comment by aried3r** [comment]
Hey! Sorry, didn't get to it until now. Trying it now with 3.5.0, seems to work fine so far :)

**Pull request merged**
