### PR TITLE
Stop Byebug after continue

### PR DESCRIPTION
**Pull request by k0kubun**
Fixes https://github.com/deivid-rodriguez/pry-byebug/issues/61

To optimize performance, I want to stop Byebug after exiting Pry's REPL.
This change must be shipped with https://github.com/deivid-rodriguez/byebug/pull/160. So dependency of byebug should be updated after the pull request is merged.

With https://github.com/deivid-rodriguez/byebug/pull/160, this worked fine in my rails application and it became faster.

### CODE REVIEW

**Comment by k0kubun** [comment]
We can't pass CI without https://github.com/deivid-rodriguez/byebug/pull/160 in byebug.

**Comment by deivid-rodriguez** [comment]
@k0kubun Thre's a couple of extra breaking changes in 7.0.

* `at_return` now receives a parameter which is the return value of the method.
* When attaching to the debugger, you might need to switch the `step_out` call and pass 4 steps instead of 3, because returns from c-methods are now taken into account too.

Hope it helps!

**Comment by k0kubun** [comment]
Thanks for your advice!

**Comment by deivid-rodriguez** [comment]
Here you go, rebase and it should be fine!

**Comment by k0kubun** [comment]
Thank you for your quick work! Rebased and Travis CI passed except for Ruby 2.0.

**Comment by deivid-rodriguez** [comment]
I see, the error in 2.0 is that same as deivid-rodriguez/byebug#183. The quick way I see of fixing it requires yet another breaking change. Too many breaking changes but I'm not going to think about it too much.

Hold on.

**Comment by deivid-rodriguez** [comment]
Ok rebase now.

**Comment by k0kubun** [comment]
Rebased and passing all tests now.

**Pull request merged**
